#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${APP_DIR}/config"   && export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR
TMPDIR="/transcode"                                             && export TMPDIR
PLEX_MEDIA_SERVER_HOME="${APP_DIR}/bin/usr/lib/plexmediaserver" && export PLEX_MEDIA_SERVER_HOME
PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6                            && export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS
PLEX_MEDIA_SERVER_INFO_VENDOR="Docker"                          && export PLEX_MEDIA_SERVER_INFO_VENDOR
PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container (hotio)"        && export PLEX_MEDIA_SERVER_INFO_DEVICE
PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"                      && export PLEX_MEDIA_SERVER_INFO_MODEL
PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(uname -r)"           && export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION

echo -e '\n##################################\n## IGNORE THE ERROR MESSAGE:    ##\n## Critical: libusb_init failed ##\n##################################\n'
exec s6-setuidgid hotio "${APP_DIR}/bin/usr/lib/plexmediaserver/Plex Media Server"
