#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
PLEX_CLAIM_TOKEN=$(mask "${PLEX_CLAIM_TOKEN}")
PLEX_ADVERTISE_URL=${PLEX_ADVERTISE_URL}
PLEX_NO_AUTH_NETWORKS=${PLEX_NO_AUTH_NETWORKS}
PLEX_BETA_INSTALL=${PLEX_BETA_INSTALL}
PLEX_PURGE_CODECS=${PLEX_PURGE_CODECS}
----------------------------------------------------------------------
"

if [[ ! -d "${CONFIG_DIR}/Temp" ]]; then
    log_inf "Creating directory [${CONFIG_DIR}/Temp]."
    mkdir "${CONFIG_DIR}/Temp"
    find "${CONFIG_DIR}/Temp" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

#################
## Configure Plex
prefFile="${CONFIG_DIR}/Preferences.xml"

function getPref {
    local key="$1"
    xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
}

function setPref {
    local key="$1"
    local value="$2"
    count="$(xmlstarlet sel -t -v "count(/Preferences/@${key})" "${prefFile}")"
    count=$((count + 0))
    if [[ $count -gt 0 ]]; then
        xmlstarlet ed --inplace --update "/Preferences/@${key}" -v "${value}" "${prefFile}"
    else
        xmlstarlet ed --inplace --insert "/Preferences"  --type attr -n "${key}" -v "${value}" "${prefFile}"
    fi
    log_inf "Set preference [${key}] to [${value}]."
}

# Create empty Preferences.xml file if it doesn't exist already
if [[ ! -f "${prefFile}" ]]; then
    log_inf "Creating empty [Preferences.xml] file."
    cat > "${prefFile}" <<-EOF
<?xml version="1.0" encoding="utf-8"?>
<Preferences/>
EOF
    find "${prefFile}" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

# Set MachineIdentifier
if [[ -z "$(getPref "MachineIdentifier")" ]]; then
    serial="$(cat /proc/sys/kernel/random/uuid)"
    setPref "MachineIdentifier" "${serial}"
fi

# Set ProcessedMachineIdentifier
if [[ -z "$(getPref "ProcessedMachineIdentifier")" ]]; then
    clientId="$(echo -n "${serial}- Plex Media Server" | sha1sum | cut -b 1-40)"
    setPref "ProcessedMachineIdentifier" "${clientId}"
fi

# Set customConnections
if [[ -n "${PLEX_ADVERTISE_URL}" ]]; then
    setPref "customConnections" "${PLEX_ADVERTISE_URL}"
fi

# Set allowedNetworks
if [[ -n "${PLEX_NO_AUTH_NETWORKS}" ]]; then
    setPref "allowedNetworks" "${PLEX_NO_AUTH_NETWORKS}"
fi

# Set TranscoderTempDirectory
if [[ -z "$(getPref "TranscoderTempDirectory")" ]]; then
    setPref "TranscoderTempDirectory" "${CONFIG_DIR}/Temp"
fi

# Set PlexOnlineToken
clientId="$(getPref "ProcessedMachineIdentifier")"
if [[ -n "${PLEX_CLAIM_TOKEN}" ]] && [[ -z "$(getPref "PlexOnlineToken")" ]]; then
    log_inf "Attempting to obtain server token from claim token..."
    loginInfo="$(curl -fsSL -X POST \
        -H 'X-Plex-Client-Identifier: '"${clientId}" \
        -H 'X-Plex-Product: Plex Media Server'\
        -H 'X-Plex-Version: 1.1' \
        -H 'X-Plex-Provides: server' \
        -H 'X-Plex-Platform: Linux' \
        -H 'X-Plex-Platform-Version: 1.0' \
        -H 'X-Plex-Device-Name: PlexMediaServer' \
        -H 'X-Plex-Device: Linux' \
        "https://plex.tv/api/claim/exchange?token=${PLEX_CLAIM_TOKEN}")"
    token="$(echo "$loginInfo" | sed -n 's/.*<authentication-token>\(.*\)<\/authentication-token>.*/\1/p')"
    if [[ -n "$token" ]]; then
        setPref "PlexOnlineToken" "${token}"
    fi
fi

######################
## Purge Codecs folder
if [[ "${PLEX_PURGE_CODECS}" == "true" ]]; then
    log_inf "Purging folder [${CONFIG_DIR}/Codecs]..."
    find "${CONFIG_DIR}/Codecs" -mindepth 1 -not -name '.device-id' -print -delete
fi

####################
## Install Plex Beta
if [[ "${PLEX_BETA_INSTALL}" == "true" ]]; then
    log_inf "Attempting beta installation..."
    do_install=true
    token="$(getPref "PlexOnlineToken")"
    if [[ -z "${token}" ]]; then
        log_wrn "No token has been found! Aborting installation."
        do_install=false
    fi
    PLEX_PASS_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=${token}" | jq -r .computer.Linux.version)
    PUBLIC_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json" | jq -r .computer.Linux.version)
    if [[ "${PUBLIC_VERSION}" == "${PLEX_PASS_VERSION}" ]] && [[ "${do_install}" == true ]]; then
        log_inf "No eligable beta for installation has been found."
        do_install=false
    fi
    INSTALLED_VERSION=$(cat "${APP_DIR}/version")
    if [[ "${INSTALLED_VERSION}" == "${PLEX_PASS_VERSION}" ]] && [[ "${do_install}" == true ]]; then
        log_inf "Already on the latest beta [${PLEX_PASS_VERSION}], no update required."
        do_install=false
    fi
    if [[ "${do_install}" == true ]]; then
        case "${BUILD_ARCHITECTURE}" in
            linux-amd64)
                architecture="amd64"
                ;;
            linux-arm64)
                architecture="arm64"
                ;;
        esac
        debfile="/tmp/plex.deb" && \
            curl -fsSL "https://downloads.plex.tv/plex-media-server-new/${PLEX_PASS_VERSION}/debian/plexmediaserver_${PLEX_PASS_VERSION}_${architecture}.deb" -o "${debfile}" && \
            rm -rf "${APP_DIR:?}/bin" && \
            mkdir "${APP_DIR}/bin" && \
            dpkg-deb -x "${debfile}" "${APP_DIR}/bin" && \
            rm -f "${debfile}" && \
            echo "${PLEX_PASS_VERSION}" > "${APP_DIR}/version" && \
            INSTALL_OK="yes"
        if [[ "${INSTALL_OK}" != "yes" ]]; then
            log_err "Installation of beta [${PLEX_PASS_VERSION}] failed! Exiting..."
            exit 1
        else
            log_inf "Installation of beta [${PLEX_PASS_VERSION}] succeeded."
        fi
    fi
fi

######################
## Install Plex Custom
INSTALLED_VERSION=$(cat "${APP_DIR}/version")
if [[ "${PLEX_BETA_INSTALL}" == "http"* ]] && [[ "${PLEX_BETA_INSTALL}" != "${INSTALLED_VERSION}" ]]; then
    log_wrn "Attempting custom installation..."
    debfile="/tmp/plex.deb" && \
        curl -fsSL "${PLEX_BETA_INSTALL}" -o "${debfile}" && \
        rm -rf "${APP_DIR:?}/bin" && \
        mkdir "${APP_DIR}/bin" && \
        dpkg-deb -x "${debfile}" "${APP_DIR}/bin" && \
        rm -f "${debfile}" && \
        echo "${PLEX_BETA_INSTALL}" > "${APP_DIR}/version" && \
        INSTALL_OK="yes"
    if [[ "${INSTALL_OK}" != "yes" ]]; then
        log_err "Installation of beta [${PLEX_PASS_VERSION}] failed! Exiting..."
        exit 1
    else
        log_inf "Installation of beta [${PLEX_PASS_VERSION}] succeeded."
    fi
fi
