#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
PLEX_CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
PLEX_ADVERTISE_URL=${PLEX_ADVERTISE_URL}
PLEX_NO_AUTH_NETWORKS=${PLEX_NO_AUTH_NETWORKS}
PLEX_BETA_INSTALL=${PLEX_BETA_INSTALL}
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/temphome"
    usermod -d "/tmp/temphome" hotio
    usermod -o -u "${PUID}" hotio
    usermod -d "${CONFIG_DIR}" hotio
    rm -rf "/tmp/temphome"
    groupmod -o -g "${PGID}" hotio
else
    echo "Running as root is not supported, please fix your PUID and PGID!"
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

echo "Applying permissions to /transcode"
chmod "=rwx" "/transcode"
chown hotio:hotio "/transcode"
