#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
ARGS=${ARGS}
DEBUG=${DEBUG}
PLEX_CLAIM=${PLEX_CLAIM}
ADVERTISE_IP=${ADVERTISE_IP}
ALLOWED_NETWORKS=${ALLOWED_NETWORKS}
PLEX_PASS=${PLEX_PASS}
PLEXAUTOSCAN_ARGS=${PLEXAUTOSCAN_ARGS}
PLEX_LOGIN=${PLEX_LOGIN}
PLEX_PASSWORD=${PLEX_PASSWORD}
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/temphome"
    usermod -d "/tmp/temphome" hotio
    usermod -o -u "${PUID}" hotio
    usermod -d "${CONFIG_DIR}" hotio
    rm -rf "/tmp/temphome"
    groupmod -o -g "${PGID}" hotio
else
    echo "Running as root is not supported, please fix your PUID and PGID!"
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

echo "Applying permissions to /transcode"
chmod "=rwx" "/transcode"
chown hotio:hotio "/transcode"

if [[ ! -d "${CONFIG_DIR}/app" ]]; then
    echo "Creating directory ${CONFIG_DIR}/app"
    mkdir "${CONFIG_DIR}/app"
    chown hotio:hotio "${CONFIG_DIR}/app"
fi

if [[ ! -d "${CONFIG_DIR}/plexautoscan" ]]; then
    echo "Creating directory ${CONFIG_DIR}/plexautoscan"
    mkdir "${CONFIG_DIR}/plexautoscan"
    chown hotio:hotio "${CONFIG_DIR}/plexautoscan"
fi
