#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

function getPref {
    local key="$1"
    
    xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
}

prefFile="${CONFIG_DIR}/app/Plex Media Server/Preferences.xml"

if [[ "${PLEX_PASS}" == "yes" ]]; then
    echo "Installing Plex Pass version..."

    token="$(getPref "PlexOnlineToken")"
    if [[ -z "${token}" ]]; then
        echo "No token has been found! Aborting installation."
        exit 0
    fi

    case "${ARCH}" in
        linux-amd64)
            architecture="amd64"
            ;;
        linux-arm64)
            architecture="arm64"
            ;;
        linux-arm)
            architecture="armhf"
            ;;
    esac

    INSTALLED_VERSION=$(dpkg-query -W -f='${Version}' plexmediaserver)
    PLEX_PASS_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=${token}" | jq -r .computer.Linux.version)

    if [[ "${INSTALLED_VERSION}" == "${PLEX_PASS_VERSION}" ]]; then
        echo "Already on the latest version \"${PLEX_PASS_VERSION}\". No update required."
        exit 0
    fi

    debfile="/tmp/plex.deb" && curl -fsSL -o "${debfile}" "https://downloads.plex.tv/plex-media-server-new/${PLEX_PASS_VERSION}/debian/plexmediaserver_${PLEX_PASS_VERSION}_${architecture}.deb" && dpkg --install --force-confold "${debfile}" && rm -f "${debfile}" && INSTALL_OK="yes"
    if [[ "${INSTALL_OK}" != "yes" ]]; then
        echo -e '\e[31m'"Installation of version \"${PLEX_PASS_VERSION}\" failed!"'\e[0m'
        exit 1
    else
        echo "Installation of version \"${PLEX_PASS_VERSION}\" succeeded."
    fi
fi
