#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

function getPref {
    local key="$1"
    
    xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
}

prefFile="${CONFIG_DIR}/app/Plex Media Server/Preferences.xml"

if [[ "${PLEX_PASS}" == "yes" ]]; then
    echo "Attempting Plex Pass beta installation..."

    token="$(getPref "PlexOnlineToken")"
    if [[ -z "${token}" ]]; then
        echo "No token has been found! Aborting installation."
        exit 0
    fi

    PLEX_PASS_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=${token}" | jq -r .computer.Linux.version)
    PUBLIC_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json" | jq -r .computer.Linux.version)

    if [[ "${PUBLIC_VERSION}" == "${PLEX_PASS_VERSION}" ]]; then
        echo "No eligable beta found! Aborting installation."
        exit 0
    fi

    INSTALLED_VERSION=$(cat "${APP_DIR}/version")
    if [[ "${INSTALLED_VERSION}" == "${PLEX_PASS_VERSION}" ]]; then
        echo "Already on the latest beta \"${PLEX_PASS_VERSION}\", no update required. Aborting installation."
        exit 0
    fi

    case "${ARCH}" in
        linux-amd64)
            architecture="amd64"
            ;;
        linux-arm64)
            architecture="arm64"
            ;;
        linux-arm)
            architecture="armhf"
            ;;
    esac

    debfile="/tmp/plex.deb" && curl -fsSL -o "${debfile}" "https://downloads.plex.tv/plex-media-server-new/${PLEX_PASS_VERSION}/debian/plexmediaserver_${PLEX_PASS_VERSION}_${architecture}.deb" && rm -rf "${APP_DIR:?}/"{etc,usr,version} && dpkg -x "${debfile}" "${APP_DIR}" && rm -f "${debfile}" && echo "${PLEX_PASS_VERSION}" > "${APP_DIR}/version" && INSTALL_OK="yes"
    if [[ "${INSTALL_OK}" != "yes" ]]; then
        echo -e '\e[31m'"Installation of beta \"${PLEX_PASS_VERSION}\" failed!"'\e[0m'
        exit 1
    else
        echo "Installation of beta \"${PLEX_PASS_VERSION}\" succeeded."
    fi
fi
