#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

INSTALLED_VERSION=$(cat "${APP_DIR}/version")

[[ -n "${PLEX_PASS}" ]] && PLEX_BETA_INSTALL=${PLEX_PASS}
if [[ "${PLEX_BETA_INSTALL}" == "http"* ]] && [[ "${PLEX_BETA_INSTALL}" != "${INSTALLED_VERSION}" ]]; then
    echo "Attempting custom installation...don't come crying for support!"

    debfile="/tmp/plex.deb" && curl -fsSL -o "${debfile}" "${PLEX_BETA_INSTALL}" && rm -rf "${APP_DIR:?}/"{etc,usr,version} && dpkg -x "${debfile}" "${APP_DIR}" && rm -f "${debfile}" && echo "${PLEX_BETA_INSTALL}" > "${APP_DIR}/version" && INSTALL_OK="yes"
    if [[ "${INSTALL_OK}" != "yes" ]]; then
        echo -e '\e[31m'"Installation of \"${PLEX_BETA_INSTALL}\" failed!"'\e[0m'
        exit 1
    else
        echo "Installation of \"${PLEX_BETA_INSTALL}\" succeeded."
    fi
fi
