#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/plexautoscan/config.json" ]]; then
    cp /etc/plexautoscan/config.json "${CONFIG_DIR}/plexautoscan/config.json"
    chown hotio:hotio "${CONFIG_DIR}/plexautoscan/config.json"
fi
