#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/plexautoscan/config.json" ]]; then
    cp /etc/plexautoscan/config.json "${CONFIG_DIR}/plexautoscan/config.json"
    chown hotio:hotio "${CONFIG_DIR}/plexautoscan/config.json"
fi


if [[ ! -f "${CONFIG_DIR}/plexautoscan/plex.token" ]] && [[ -n ${PLEX_LOGIN} ]] && [[ -n ${PLEX_PASSWORD} ]]; then
    echo "Trying to get a token for PlexAutoscan..."
    curl -fsSL -u "${PLEX_LOGIN}":"${PLEX_PASSWORD}" 'https://plex.tv/users/sign_in.json' -X POST -H 'X-Plex-Client-Identifier: '"$(uuidgen)" -H 'X-Plex-Product: PlexAutoscan' -H 'X-Plex-Provides: controller' -H 'X-Plex-Device: '"$(uname -r)" \
        > "${CONFIG_DIR}/plexautoscan/plex.token" && chown hotio:hotio "${CONFIG_DIR}/plexautoscan/plex.token" && echo "Token obtained successfully!"
fi

if [[ -f "${CONFIG_DIR}/plexautoscan/plex.token" ]]; then
    echo "Updating \"config.json\" with token from \"plex.token\"..."
    token="$(jq -r .[].authentication_token "${CONFIG_DIR}/plexautoscan/plex.token")"
    if [[ -n ${token} ]] && [[ ${token} != null ]]; then
        sed -i -n "s#\"PLEX_TOKEN\": \".*\",#\"PLEX_TOKEN\": \"${token}\",#g" "${CONFIG_DIR}/plexautoscan/config.json"
        echo "Token updated successfully!"
    else
        echo "Couldn't find token!"
    fi
fi
