#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ "${DISABLE_RELAY}" == "no" ]] && [[ -f "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay DISABLED" ]] && [[ ! -f "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay" ]]; then
    echo "Re-enabling Plex Relay..."
    mv "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay DISABLED" "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay"
elif [[ "${DISABLE_RELAY}" == "yes" ]] && [[ -f "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay" ]]; then
    echo "Disabling Plex Relay..."
    mv "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay" "${APP_DIR}/usr/lib/plexmediaserver/Plex Relay DISABLED"
fi
