#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ "${DISABLE_RELAY}" == "no" ]] && [[ -f "/usr/lib/plexmediaserver/Plex Relay DISABLED" ]] && [[ ! -f "/usr/lib/plexmediaserver/Plex Relay" ]]; then
    mv "/usr/lib/plexmediaserver/Plex Relay DISABLED" "/usr/lib/plexmediaserver/Plex Relay"
elif [[ "${DISABLE_RELAY}" == "yes" ]] && [[ -f "/usr/lib/plexmediaserver/Plex Relay" ]]; then
    mv "/usr/lib/plexmediaserver/Plex Relay" "/usr/lib/plexmediaserver/Plex Relay DISABLED"
fi
